# This is a basic workflow that is manually triggered

name: Full Branch Manual Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      DEBUG:
        description: 'If DEBUGGING and artifact creation should be enabled'
        default: false
        required: false
        type: boolean
      ValidateOnly:
        description: 'Validation only'
        default: false
        required: false
        type: boolean
      RunTests:
        description: 'Run Local Tests?'
        default: false
        required: false
        type: boolean
      PLSPROD:
        description: 'Use production PLS Endpoint'
        default: false
        required: false
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  UserValidation:
    runs-on: ubuntu-latest
    outputs:
      UserValidation: ${{ steps.checkUserMember.outputs.isTeamMember }}
    steps:
      - name: User Validation Initialization
        run: echo Running on branch ${GITHUB_REF##*/}

      - name: Retrieve User Membership
        uses: tspascoal/get-user-teams-membership@v2
        id: checkUserMember
        with:
          username: ${{ github.actor }}
          team: 'Salesforce Developers'
          GITHUB_TOKEN: ${{ secrets.QBCC_PAT_FOR_WORKFLOWS }}

      - name: Validate User And Terminate Step
        run: |
          if ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }} 
          then
            echo "Is Member"
          else 
            echo "Is Not Member"
            exit 1            
          fi
      - name: User Validation Complete
        run: 
          echo "User Validation Complete"