on: 
  [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Fun-Park/hello-world-javascript-action@master
        with:
          who-to-greet: 'Surahman the hexo'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  hello_you_job:
    runs-on: ubuntu-latest
    name: Another job to say hello
    steps:
        - name: Hello you action step
          id: hello2
          uses: Fun-Park/hello-world-javascript-action@master
          with:
                who: 'Another Surahman'
        # Use the output from the `hello` step
        - name: Get the output timestamp
          run: echo "The time was ${{ steps.hello2.outputs.when }}"
